# Generated by Django 4.1.5 on 2023-01-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quality',
            new_name='quantity',
        ),
    ]
